/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author vitor
 */
public class formItens extends javax.swing.JInternalFrame {

    private Object btntextAddItens;

    /**
     * Creates new form formClientes
     */
    public formItens() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textAddItens = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botaotSalvar = new javax.swing.JButton();
        checkAdicionar = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Adicionar Itens:");

        textAddItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddItensActionPerformed(evt);
            }
        });

        jLabel3.setText("Itens :");

        botaotSalvar.setText("Salvar");
        botaotSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaotSalvarActionPerformed(evt);
            }
        });

        checkAdicionar.setText("Adicionar");
        checkAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textAddItens, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(checkAdicionar)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaotSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(textAddItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(checkAdicionar)
                .addGap(30, 30, 30)
                .addComponent(botaotSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textAddItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddItensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddItensActionPerformed

    private void checkAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAdicionarActionPerformed

    private void botaotSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaotSalvarActionPerformed

    }//GEN-LAST:event_botaotSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaotSalvar;
    private javax.swing.JCheckBox checkAdicionar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textAddItens;
    // End of variables declaration//GEN-END:variables
}
