/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author Mikael Vitor Santos
 */
public class formPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form formPrincipal
     */
    public formPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpnDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivos = new javax.swing.JMenu();
        menuArquivostClientes = new javax.swing.JMenuItem();
        menuArquivostProdutos = new javax.swing.JMenuItem();
        menuArquivostUsuarios = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuArquivostSairdoSistema = new javax.swing.JMenuItem();
        menuGestao = new javax.swing.JMenu();
        menuGestaotRecepçao = new javax.swing.JMenuItem();
        menuGestaotBancodeDados = new javax.swing.JMenuItem();
        menuGestaotOrganizaçao = new javax.swing.JMenuItem();
        menuGestaotDistribuiçao = new javax.swing.JMenuItem();
        menuFerramentas = new javax.swing.JMenu();
        menuFerramentastRastreamento = new javax.swing.JMenuItem();
        menuFerramentastCriarRelatorios = new javax.swing.JMenuItem();
        menuFerramentastCodigodeBarras = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuFerramentastTrocarSenha = new javax.swing.JMenuItem();
        menuFerramentastTrocarUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Almoxarifado");

        javax.swing.GroupLayout dpnDesktopLayout = new javax.swing.GroupLayout(dpnDesktop);
        dpnDesktop.setLayout(dpnDesktopLayout);
        dpnDesktopLayout.setHorizontalGroup(
            dpnDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        dpnDesktopLayout.setVerticalGroup(
            dpnDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        menuArquivos.setText("Arquivos");

        menuArquivostClientes.setText("Itens");
        menuArquivostClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivostClientesActionPerformed(evt);
            }
        });
        menuArquivos.add(menuArquivostClientes);

        menuArquivostProdutos.setText("Produtos");
        menuArquivostProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivostProdutosActionPerformed(evt);
            }
        });
        menuArquivos.add(menuArquivostProdutos);

        menuArquivostUsuarios.setText("Usuários");
        menuArquivostUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivostUsuariosActionPerformed(evt);
            }
        });
        menuArquivos.add(menuArquivostUsuarios);
        menuArquivos.add(jSeparator2);

        menuArquivostSairdoSistema.setText("Sair do Sistema");
        menuArquivostSairdoSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivostSairdoSistemaActionPerformed(evt);
            }
        });
        menuArquivos.add(menuArquivostSairdoSistema);

        jMenuBar1.add(menuArquivos);

        menuGestao.setText("Gestão");
        menuGestao.setToolTipText("");

        menuGestaotRecepçao.setText("Recepção");
        menuGestaotRecepçao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestaotRecepçaoActionPerformed(evt);
            }
        });
        menuGestao.add(menuGestaotRecepçao);

        menuGestaotBancodeDados.setText("Banco de Dados");
        menuGestaotBancodeDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestaotBancodeDadosActionPerformed(evt);
            }
        });
        menuGestao.add(menuGestaotBancodeDados);

        menuGestaotOrganizaçao.setText("Organização");
        menuGestaotOrganizaçao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestaotOrganizaçaoActionPerformed(evt);
            }
        });
        menuGestao.add(menuGestaotOrganizaçao);

        menuGestaotDistribuiçao.setText("Distribuição");
        menuGestaotDistribuiçao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestaotDistribuiçaoActionPerformed(evt);
            }
        });
        menuGestao.add(menuGestaotDistribuiçao);

        jMenuBar1.add(menuGestao);

        menuFerramentas.setText("Ferramentas");

        menuFerramentastRastreamento.setText("Rastreamento");
        menuFerramentastRastreamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFerramentastRastreamentoActionPerformed(evt);
            }
        });
        menuFerramentas.add(menuFerramentastRastreamento);

        menuFerramentastCriarRelatorios.setText("Criar Relatórios");
        menuFerramentastCriarRelatorios.setToolTipText("");
        menuFerramentastCriarRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFerramentastCriarRelatoriosActionPerformed(evt);
            }
        });
        menuFerramentas.add(menuFerramentastCriarRelatorios);

        menuFerramentastCodigodeBarras.setText("Código de Barras ");
        menuFerramentastCodigodeBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFerramentastCodigodeBarrasActionPerformed(evt);
            }
        });
        menuFerramentas.add(menuFerramentastCodigodeBarras);
        menuFerramentas.add(jSeparator1);

        menuFerramentastTrocarSenha.setText("Trocar Senha");
        menuFerramentastTrocarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFerramentastTrocarSenhaActionPerformed(evt);
            }
        });
        menuFerramentas.add(menuFerramentastTrocarSenha);

        menuFerramentastTrocarUsuario.setText("Trocar Usuário");
        menuFerramentastTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFerramentastTrocarUsuarioActionPerformed(evt);
            }
        });
        menuFerramentas.add(menuFerramentastTrocarUsuario);

        jMenuBar1.add(menuFerramentas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGestaotRecepçaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestaotRecepçaoActionPerformed
      formRecepçao mRecepçao = new formRecepçao();
      dpnDesktop.add(mRecepçao);
      mRecepçao.show();
    }//GEN-LAST:event_menuGestaotRecepçaoActionPerformed

    private void menuArquivostUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivostUsuariosActionPerformed
       formUsuarios mUsuarios = new formUsuarios();
       dpnDesktop.add(mUsuarios);
       mUsuarios.show();
    }//GEN-LAST:event_menuArquivostUsuariosActionPerformed

    private void menuArquivostClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivostClientesActionPerformed
        formItens mItens = new formItens();
        dpnDesktop.add(mItens);
        mItens.show();
        
    }//GEN-LAST:event_menuArquivostClientesActionPerformed

    private void menuArquivostSairdoSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivostSairdoSistemaActionPerformed
        formSairdoSistema mSairdoSistema = new formSairdoSistema();
        dpnDesktop.add(mSairdoSistema);
        mSairdoSistema.show();
    }//GEN-LAST:event_menuArquivostSairdoSistemaActionPerformed

    private void menuGestaotBancodeDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestaotBancodeDadosActionPerformed
         formBancodeDados mBancodeDados = new formBancodeDados();
         dpnDesktop.add(mBancodeDados);
         mBancodeDados.show();
    }//GEN-LAST:event_menuGestaotBancodeDadosActionPerformed

    private void menuFerramentastRastreamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFerramentastRastreamentoActionPerformed
         formRastreamento mRastreamento = new formRastreamento();
         dpnDesktop.add(mRastreamento);
         mRastreamento.show();
    }//GEN-LAST:event_menuFerramentastRastreamentoActionPerformed

    private void menuFerramentastCodigodeBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFerramentastCodigodeBarrasActionPerformed
         formCodigodeBarras mCodigodeBarras = new formCodigodeBarras();
         dpnDesktop.add(mCodigodeBarras);
         mCodigodeBarras.show();
    }//GEN-LAST:event_menuFerramentastCodigodeBarrasActionPerformed

    private void menuFerramentastCriarRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFerramentastCriarRelatoriosActionPerformed
         formCriarRelatorios mCriarRelatorios = new formCriarRelatorios();
         dpnDesktop.add(mCriarRelatorios);
         mCriarRelatorios.show();
    }//GEN-LAST:event_menuFerramentastCriarRelatoriosActionPerformed

    private void menuFerramentastTrocarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFerramentastTrocarSenhaActionPerformed
         formTrocarSenha mTrocarSenha = new formTrocarSenha();
         dpnDesktop.add(mTrocarSenha);
         mTrocarSenha.show();
    }//GEN-LAST:event_menuFerramentastTrocarSenhaActionPerformed

    private void menuFerramentastTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFerramentastTrocarUsuarioActionPerformed
         formTrocarUsuario mTrocarUsuario = new formTrocarUsuario();
         dpnDesktop.add(mTrocarUsuario);
         mTrocarUsuario.show();
         
    }//GEN-LAST:event_menuFerramentastTrocarUsuarioActionPerformed

    private void menuArquivostProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivostProdutosActionPerformed
         formProdutos mProdutos = new formProdutos();
         dpnDesktop.add(mProdutos);
         mProdutos.show();
    }//GEN-LAST:event_menuArquivostProdutosActionPerformed

    private void menuGestaotOrganizaçaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestaotOrganizaçaoActionPerformed
         formOrganização mOrganização = new formOrganização();
         dpnDesktop.add(mOrganização);
         mOrganização.show();
    }//GEN-LAST:event_menuGestaotOrganizaçaoActionPerformed

    private void menuGestaotDistribuiçaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestaotDistribuiçaoActionPerformed
         formDistribuiçao mDistribuiçao = new formDistribuiçao();
         dpnDesktop.add(mDistribuiçao);
         mDistribuiçao.show();
    }//GEN-LAST:event_menuGestaotDistribuiçaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpnDesktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menuArquivos;
    private javax.swing.JMenuItem menuArquivostClientes;
    private javax.swing.JMenuItem menuArquivostProdutos;
    private javax.swing.JMenuItem menuArquivostSairdoSistema;
    private javax.swing.JMenuItem menuArquivostUsuarios;
    private javax.swing.JMenu menuFerramentas;
    private javax.swing.JMenuItem menuFerramentastCodigodeBarras;
    private javax.swing.JMenuItem menuFerramentastCriarRelatorios;
    private javax.swing.JMenuItem menuFerramentastRastreamento;
    private javax.swing.JMenuItem menuFerramentastTrocarSenha;
    private javax.swing.JMenuItem menuFerramentastTrocarUsuario;
    private javax.swing.JMenu menuGestao;
    private javax.swing.JMenuItem menuGestaotBancodeDados;
    private javax.swing.JMenuItem menuGestaotDistribuiçao;
    private javax.swing.JMenuItem menuGestaotOrganizaçao;
    private javax.swing.JMenuItem menuGestaotRecepçao;
    // End of variables declaration//GEN-END:variables
}
